### ISSUE TITLE
Create a product roadmap

### ISSUE THREAD

**Issue by Auspicus** [Desarol/drupal-jsonapi-client#9]
## Few things so far:
- [ ] New API to follow JSON:API semantics religiously
- [ ] Provide a way to pull entity definitions locally (default values, etc) and cache them for continued usage across page refreshes
- [ ] Integrate devour-client to reduce / remove heavy lifting of serialization, etc
